### ISSUE TITLE
Create a page to list all authors

### ISSUE THREAD

**Issue by jamietanna** [AnnaDodson/hacktoberfest-website#12]
It'd be cool to see a list of everyone helping to contribute over the month, and at least list their names, but would also be awesome to get a link to their GitHub account, too

**Comment by beforan** [comment]
not committing to working on this :P but:

conceivably a cool way to list hacktoberfest contributors without maintaining a list manually would be to write some JS that hits the GitHub API and provides a distinct list of users who've raised (or had merged) Pull Requests to the repo during October. That would be easy to get links to their GitHub profiles from too.

Unless you had something else in mind for what the list should be (e.g. Post Authors rather than all PR contributors).

**Comment by AnnaDodson** [comment]
A list of all the names of the people who have raised PRs to the repo would be great. The GitHub API definitely has an endpoint for this

**Comment by jamietanna** [comment]
That sounds like a plan - it looks like there are two Ruby Gems to do similar things in Jekyll itself - https://rubygems.org/gems/jekyll-git_metadata and https://rubygems.org/gems/jekyll-github-metadata

**Comment by chrisemerson** [comment]
Perhaps rename the authors yml file to contributors, which will enable other metadata to be saved (website, twitter, maybe bio). Linked to #16 too.

**Comment by AnnaDodson** [comment]
Closed in #34
